### ISSUE TITLE
Usage information

### ISSUE THREAD

**Issue by izhukov1992** [whitespy/django-simple-metatags#1]
This is the best SEO module I have ever seen!
But I waste some time to understand how to use it properly. So, please, add information to the README about usage of `include_meta_tags` tag. Because it has to be used with an instance `{% include_meta_tags object %}`:
```
{% load meta_tags %}
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    {% block meta_tags %}
        {% include_meta_tags object %}
    {% endblock %}
</head>
```

**Comment by whitespy** [comment]
Done.
