### ISSUE TITLE
ValueError at /admin/logout/

### ISSUE THREAD

**Issue by guldmytro** [whitespy/django-simple-metatags#5]
Hi.
I installed your package. Then the standard authorization system stopped working correctly. What could be the reason?

![Знімок екрану з 2021-11-06 12-53-45](https://user-images.githubusercontent.com/42564802/140607079-ba6f971c-b69e-44d7-b9ae-4428cbc1364f.png)

**Comment by whitespy** [comment]
Hi! Looks like some model of your project has primary key with string type (CharField, etc). Meta tags may not be attached to models where primary key type is not auto-incrementing or positive integer. The documentation of this package says about this case.
